name: yoori_ecommerce
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.4+5

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  awesome_dialog: ^2.2.1
  badges: ^2.0.3
  cached_network_image: 
  carousel_slider: ^4.0.0
  change_app_package_name: ^1.1.0
  connectivity_plus: ^2.2.1
  country_pickers: ^2.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  firebase_analytics: 
  firebase_auth: 
  firebase_core: 
  flutter:
    sdk: flutter
  flutter_countdown_timer: ^4.1.0
  flutter_facebook_auth: ^4.4.0+1
  flutter_holo_date_picker: ^1.0.3
  flutter_inappwebview: ^5.4.3+7
  flutter_isolate: ^2.0.2
  flutter_localizations:
    sdk: flutter
  flutter_rating_bar: ^4.0.1
  flutter_screenutil: ^5.0.1
  flutter_slidable: ^2.0.0
  flutter_spinkit: ^5.1.0
  flutter_staggered_grid_view: ^0.6.2
  flutter_svg: ^1.0.3
  flutter_switch: ^0.3.2
  flutter_widget_from_html: ^0.8.5
  fluttertoast: ^8.0.9
  get: ^4.6.1
  get_storage: ^2.0.3
  google_sign_in: ^5.2.4
  hive: ^2.0.5
  hive_flutter: ^1.1.0
  http: ^0.13.4
  image_picker: ^0.8.5+3
  intl: ^0.17.0
  lottie: 
  material_design_icons_flutter: ^5.0.6595
  modal_bottom_sheet: ^2.1.0
  money_formatter: ^0.0.3
  new_version: ^0.3.1
  onesignal_flutter: ^3.4.1
  open_file: ^3.2.1
  package_info_plus: 
  pagination_view: ^2.0.0
  path: ^1.7.0
  path_provider: ^2.0.1
  pin_code_fields: ^7.4.0
  pinput: ^2.2.11
  provider: ^6.0.2
  pull_to_refresh: ^2.0.0
  ribbon_widget: ^1.0.5
  share_plus: ^4.0.10
  shimmer: ^2.0.0
  sign_in_with_apple: ^4.1.0
  store_redirect: ^2.0.1
  syncfusion_flutter_pdfviewer: ^20.2.39-beta
  the_apple_sign_in: ^1.1.1
  timelines: ^0.1.0
  url_launcher: ^6.0.3
  photo_view: ^0.14.0
  uri_to_file: ^0.2.0

dev_dependencies:
  build_runner: ^2.1.7
  flutter_launcher_icons: ^0.9.2
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logos/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/icons/details/
    - assets/icons/track_order/
    - assets/fonts/
    - assets/images/
    - assets/logos/
    - assets/lottie/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins LightItalic
      fonts:
        - asset: assets/fonts/Poppins-LightItalic.ttf
